version: "3.8"

networks:
    custom_network:
        driver: bridge

services:
    web:
        image: nginx
        container_name: nginx-google
        restart: unless-stopped
        ports:
            - "94:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            - custom_network
        depends_on:
            - php-fpm
            - mysql

    php-fpm:
        container_name: php-fpm-google
        build: ./docker/php
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini
        networks:
            - custom_network
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0.42
        container_name: mysql-google
        restart: unless-stopped
        ports:
            -   "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        command:
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --host-cache-size=0  # Вместо deprecated --skip-host-cache
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_ROOT_PASSWORD}" ]
            interval: 10s
            timeout: 5s
            retries: 10
        networks:
            - custom_network
volumes:

    mysql_data:
        driver: local
